import type { Metadata } from "next";
import { Syne, Titillium_Web, Nunito_Sans, Rajdhani } from "next/font/google";
import "@/styles/globals.css";

const rajdhani = Rajdhani({
  weight: ["300", "400", "600", "700"],
  variable: "--font-rajdhani",
  subsets: ["latin"],
});
const titilliumWeb = Titillium_Web({
  weight: ["200", "300", "400", "600", "700", "900"],
  variable: "--font-titillium-web",
  subsets: ["latin"],
});

const sync = Syne({
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-sync",
  subsets: ["latin"],
})
const nunito = Nunito_Sans({
  weight: ["200", "300", "400", "600", "700", "900"],
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${titilliumWeb.variable} ${sync.variable} ${nunito.variable}  ${rajdhani.variable}antialiased`}
      >
        {children}
      </body>
    </html >
  );
}
